version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

workflows:
  dagger:
    jobs:
      - build