---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashitalks
  labels:
    app: hashitalks
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: hashitalks
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hashitalks
    spec:
      containers:
      - name: app
        image: nicholasjackson/hashitalks2024:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hashitalks
spec:
  selector:
    app.kubernetes.io/name: hashitalks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer