name: "Dagger Build and Deploy"

on: push

env:
  VAULT_ADDR: https://vault-cluster-public-vault-0bbbdae6.9eb86982.z1.hashicorp.cloud:8200/
  VAULT_NAMESPACE: /admin/dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0