name: "Dagger Build and Deploy"

on: push

env:
  VAULT_ADDR: https://vault-cluster-public-vault-0bbbdae6.9eb86982.z1.hashicorp.cloud:8200/
  VAULT_NAMESPACE: /admin/dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch OIDC Token
        uses: dagger/dagger-for-github@v5
        with:
          verb: call 
          module: ./dagger/build
          args: all --src=. --vault-addr=${VAULT_ADDR} --vault-namespace=${VAULT_NAMESPACE} --actions-request-token=ACTIONS_ID_TOKEN_REQUEST_TOKEN --actions-token-url=${ACTIONS_ID_TOKEN_REQUEST_URL} 
          version: "0.9.9"